language: python
dist: bionic
python:
  - 3.6
  - 3.7
  - 3.8
install:
  - pip install -r requirements.txt -r requirements-test.txt
script:
  - make test
  - python setup.py install
  - ubuntu-cloud-image -h
