name: ubuntu-cloud-image
summary: Find the latest Ubuntu Images for clouds
description: |
  TODO

version: git
grade: stable
confinement: strict
environment:
    LC_ALL: C.UTF-8
    LANG: C.UTF-8

apps:
    ubuntu-cloud-image:
        command: bin/ubuntu-cloud-image
        plugs:
            - browser-support
            - desktop
            - network

parts:
    ubuntu-cloud-image:
        plugin: python
        source: https://github.com/powersj/ubuntu-cloud-image
        source-type: git
